// Generated by ReScript, PLEASE EDIT WITH CARE


function insertIntoElement(element, method, value, custom) {
  switch (method) {
    case "" :
        break;
    case "HTML" :
        element.innerHtml = value;
        break;
    case "Txt" :
        element.innerText = value;
        break;
    case "Val" :
        element.value = value;
        break;
    default:
      throw {
            RE_EXN_ID: "Match_failure",
            _1: [
              "jquery.res",
              18,
              2
            ],
            Error: new Error()
          };
  }
  return custom;
}

function $(id) {
  var element = window.document.getElementById(id);
  var custom_val = function (value) {
    return insertIntoElement(element, "Val", value, custom);
  };
  var custom_text = function (value) {
    return insertIntoElement(element, "Txt", value, custom);
  };
  var custom_html = function (value) {
    return insertIntoElement(element, "HTML", value, custom);
  };
  var custom = {
    val: custom_val,
    text: custom_text,
    html: custom_html
  };
  return custom;
}

export {
  insertIntoElement ,
  $ ,
}
/* No side effect */
